ahead_dist: 2
alpha: 0.5
batch_size: 128
beta: 3.5
delta: 4
encoder_channel: 16
epsilon: 1
fear_weight: 0.5
knodes: 5
learning_rate: 0.00015554800362034102
min_gamma: 0.001
num_epochs: 60
num_workers: 8
optimizer: adamw
risk_threshold: 0.5
trav_threshold: 0.5
weight_decay: 0.001
